name: TF Init
description: Initializes tfvars, tf backend and runs terraform init.
inputs:
  region:
    description: The digital ocean region.
    required: true
  s3_endpoint:
    description: The fully qualified https endpoint for s3 storage.
    required: true
  s3_bucket:
    description: The name of the s3 bucket.
    required: true
  s3_state_key:
    description: The name of the blob in the s3 bucket.
    required: true
  cwd:
    description: The working directory to apply commands in.
    default: "."
outputs:
  tfvars_file:
    description: The name of the tfvars file that was generated.
    value: "generated.tfvars"
runs:
  using: composite
  steps:
    - name: mk tfvars
      shell: pwsh
      working-directory: ${{ inputs.cwd }}
      run: |
        write-host "Generating tfvars:"
        @"
        do_region = "$env:region"
        "@ > generated.tfvars
        cat generated.tfvars
    - name: mk tf backend
      shell: pwsh
      working-directory: ${{ inputs.cwd }}
      run: |
        @"
        terraform {
          backend "s3" {
            endpoints = {
              s3 = "$env:s3_endpoint"
            }

            bucket = "$env:s3_bucket"
            key    = "$env:s3_state_key"

            # Deactivate a few AWS-specific checks
            skip_credentials_validation = true
            skip_requesting_account_id  = true
            skip_metadata_api_check     = true
            skip_region_validation      = true
            skip_s3_checksum            = true
            region                      = "us-east-1"
          }
        }
        "@ > backend.tf
        cat backend.tf
    - name: init
      shell: pwsh
      working-directory: ${{ inputs.cwd }}
      run: terraform init
