name: TF Ini
on:
  workflow_call:
    inputs:
      REGION:
        type: string
        required: true
      S3_ENDPOINT:
        type: string
        required: true
      S3_BUCKET:
        type: string
        required: true
      S3_STATE_KEY:
        type: string
        required: true
      WORKING_DIRECTION:
        type: string
        default: "."
    outputs:
      TF_VARS:
        value: "generated.tfvars"
jobs:
  InitTerraform:
    runs-on: ubuntu-latest
    environment: primary
    env:
      REGION: ${{ inputs.REGION }}
      S3_ENDPOINT: ${{ inputs.S3_ENDPOINT }}
      S3_BUCKET: ${{ inputs.S3_BUCKET }}
      S3_STATE_KEY: ${{ inputs.S3_STATE_KEY }}
    steps:
      - name: mk tfvars
        shell: pwsh
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          write-host "Generating tfvars:"
          @"
          do_region = "$env:REGION"
          "@ > generated.tfvars
          cat generated.tfvars
      - name: mk tf backend
        shell: pwsh
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: |
          @"
          terraform {
            backend "s3" {
              endpoints = {
                s3 = "$env:S3_ENDPOINT"
              }

              key    = "$env:S3_STATE_KEY"
              bucket = "$env:S3_BUCKET"

              # Deactivate a few AWS-specific checks
              skip_credentials_validation = true
              skip_requesting_account_id  = true
              skip_metadata_api_check     = true
              skip_region_validation      = true
              skip_s3_checksum            = true
              region                      = "us-east-1"
            }
          }
          "@ > backend.tf
          cat backend.tf
      - name: init
        shell: pwsh
        working-directory: ${{ inputs.WORKING_DIRECTORY }}
        run: terraform init
